name: Publish Helm Chart

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  release-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

      - name: Build Helm Chart Dependencies
        run: |
          for dir in charts/*; do
            if [ -d "$dir" ] && [ -f "${dir}/Chart.yaml" ]; then
              helm dependency build "$dir"
            else
              echo "$dir is not a Helm chart directory."
            fi
          done

      - name: Package Helm Charts
        run: |
          mkdir ./package
          helm package charts/* --destination ./package

      - name: Update Helm repo index
        run: |
          cd package
          helm repo index . --url https://CryptoManufaktur-io.github.io/eth-staking-charts/
          cd ..

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: 'gh-pages'
          path: 'gh-pages'

      - name: Commit and push changes
        run: |
          cp -r package/* gh-pages/
          cd gh-pages
          git add .
          git commit -m "Publish Helm charts"
          git push origin gh-pages

